---

- hosts: ROUTERS
  gather_facts: false
  connection: local

  tasks:
    - name: Configure Interface
      ios_config:
       parents: int ethernet 0/3
       lines:
        - desc Test2
        - ip address 2.2.2.3 255.255.255.0
  #tasks:
    - name: Configure OSPF Area
      ios_config:
       parents: router ospf 101
       lines:
        - network 2.2.2.0 0.0.0.255 area 1
       before:
        - no router ospf 100
